### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by SlimeDog** [flori-schwa/VarLightOld#19]
Spigot 1.15.1 (Jenkins 2552)
VarLight 1.7.1-MC-1.15.1

I assume that I have misunderstood the instructions. My intent is not to log the VarLight saves. This is logged every 5 minutes
```
[17:59:33] [Server thread/INFO]: [VarLight] Light Sources persisted for World "world", Files modified: 0, Files deleted: 0
```
despite configuration
```
autosave: 5
autosave-logpersist: 'false'
```
Please advise what I have done wrong.

**Comment by flori-schwa** [comment]
Remove the quotes around `false`. Older versions of the plugin erroneously saved them with the quotes by default, which has now been fixed.

**Comment by SlimeDog** [comment]
OK, changed configuration to
```
item: "minecraft:glowstone_dust"
autosave: -5
autosave-logpersist: true
requiredPermission: varlight.use
whitelist:
- world
blacklist: []
vldb-deflated: true
```
I assumed that VarLight instances would be saved only after **save-all**, and the saves should be logged. That is not what appears to happen. The persists are not logged after **save-all**. They are still logged every 5 minutes, but no files are modified (there should be one).

**Comment by flori-schwa** [comment]
You have a negative value set, meaning "save light sources every time the world gets saved" which happens automatically. I will look into it tomorrow. That part of the code needs refactoring badly anyway.

**Comment by SlimeDog** [comment]
Thanks. The file timestamp has not changed, since I changed the config. So it isn't being saved at all. (Which is not an issue for me, since it doesn't change on my server, but could be for others.)

**Comment by flori-schwa** [comment]
[Should be easier to configure in latest release](https://github.com/flori-schwa/VarLight/releases/tag/1.8)
