### ISSUE TITLE
Paper 1.15.1 Patch

### ISSUE THREAD

**Issue by notkohrt** [flori-schwa/VarLightOld#21]
I can't get VarLight 1.8 to work on my 1.15.1 paper server. The plugin runs, boots fine. It's only effected when you attempt to change a blocks light level. Here's my console when you right click with glowstone. https://mcpaste.io/ea1ef9fc635a84bc

**Comment by flori-schwa** [comment]
Are you using the latest version of LightAPI?

**Comment by notkohrt** [comment]
> Are you using the latest version of LightAPI?

Light API version 3.2.8
VarLight-1.8-MC-1.15.1.jar
Minecraft 1.15.1
Paper-latest-1.15.jar

**Comment by flori-schwa** [comment]
Latest version of LightAPI is 3.4.2: https://www.spigotmc.org/resources/lightapi-fork.48247/

**Comment by notkohrt** [comment]
> Latest version of LightAPI is 3.4.2: https://www.spigotmc.org/resources/lightapi-fork.48247/

Awesome. Thank you so much. I was on the wrong resource page.

**Comment by flori-schwa** [comment]
Did the LightAPI update fix the problem?

**Comment by notkohrt** [comment]
> Did the LightAPI update fix the problem?

Works perfectly, thank you!
