### ISSUE TITLE
CatServer Not available

### ISSUE THREAD

**Issue by Binket** [flori-schwa/VarLightOld#23]
CatServer 
git-CatServerAsync-1.12.2-20aba10 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2847)
https://i.loli.net/2020/02/06/DXNHaGvZey7upoJ.png

**Comment by flori-schwa** [comment]
can you please give me the whole server log file?

**Comment by Binket** [comment]
https://paste.ubuntu.com/p/QFZ67hh6ZC/

**Comment by flori-schwa** [comment]
Try it with this version and tell me if the error has been fixed.
[VarLight-cce4168-MC-1.12.2.zip](https://github.com/flori-schwa/VarLight/files/4169962/VarLight-cce4168-MC-1.12.2.zip)

**Comment by Binket** [comment]
No.
server log ;
https://paste.ubuntu.com/p/F64sFRQSQX/

**Comment by flori-schwa** [comment]
Send me the "world/varlight" folder, the files seem to be corrupt, I'll try to fix them

**Comment by Binket** [comment]
Thanks.

[varlight.zip](https://github.com/flori-schwa/VarLight/files/4174005/varlight.zip)

**Comment by flori-schwa** [comment]
The file contains no useful data, delete the "world/varlight" folder and try again

**Comment by Binket** [comment]
same
https://paste.ubuntu.com/p/TVRQwv88Sf/

**Comment by flori-schwa** [comment]
The plugin was developed for vanilla minecraft. I never expected

a) for a spigot/forge hybrid to exist
b) someone to actually install my plugin on such a server

The issue is caused here: https://github.com/flori-schwa/VarLight/blob/1.8.2/Core/src/me/shawlaf/varlight/spigot/persistence/WorldLightSourceManager.java#L72

The plugin only knows the three vanilla dimensions overworld, nether and end. You seem to also have a mod installed which adds more dimensions, the plugin doesn't know where exactly the "region" folder is located.

**Comment by Binket** [comment]
:(    k. Thank you

**Comment by flori-schwa** [comment]
I am currently working on another way to determine the "region" folders location, no need to close the issue

**Comment by flori-schwa** [comment]
Try again with this version
[VarLight-aad1b2d-MC-1.12.2.zip](https://github.com/flori-schwa/VarLight/files/4174109/VarLight-aad1b2d-MC-1.12.2.zip)

**Comment by Binket** [comment]
https://paste.ubuntu.com/p/9hyHnFxtCn/

**Comment by Binket** [comment]
OMG Too much lines:4845 
[Server thread/INFO] [me.shawlaf.varlight.spigot.VarLightPlugin]: [VarLight] [MoveVarlightRootFolder] Migrated World "DIM-1"

**Comment by flori-schwa** [comment]
Is it spamming that one line?

**Comment by Binket** [comment]
yep.

**Comment by flori-schwa** [comment]
Try again with this one
[VarLight-f67ce92-MC-1.12.2.zip](https://github.com/flori-schwa/VarLight/files/4174137/VarLight-f67ce92-MC-1.12.2.zip)

**Comment by Binket** [comment]
wow. it works .Great
![20200208194205](https://user-images.githubusercontent.com/49503376/74084541-1aefaf00-4aab-11ea-833d-5ce62a243383.png)

**Comment by Binket** [comment]
![20200208194308](https://user-images.githubusercontent.com/49503376/74084561-42467c00-4aab-11ea-93df-b554709d6a4e.png)

**Comment by Binket** [comment]
Thank you very much!

**Comment by flori-schwa** [comment]
No problem, building the release for this bugfix right now

**Comment by flori-schwa** [comment]
Fixed in [1.8.3](https://github.com/flori-schwa/VarLight/releases/tag/1.8.3)
