### ISSUE TITLE
Bug/Request

### ISSUE THREAD

**Issue by Donutnut1** [flori-schwa/VarLightOld#26]
Not sure if it's a bug or something that's purposely implemented, but it's currently not possible to use the plugin on stairs, slabs, walls/fences or glass (or glass panes) on 1.15.

We're currently needing a light plugin that will work on glass, the way addlight used to. If it's not purposely done due to issues, would it be possible to implement this for us?

Thank you

**Comment by flori-schwa** [comment]
Non-Full / Non-Opaque blocks are currently not allowed as some can be quite buggy (for example tall grass was really buggy), but I can some more blocks and perhaps "whitelist" them

**Comment by flori-schwa** [comment]
More Blocks will be able to be turned into Light Sources in the Next release: https://github.com/flori-schwa/VarLight/blob/dev/v1_15_R1/resources/VarLight/data/varlight/tags/blocks/allowed_blocks.json

Stairs and Slabs will be allowed. Fences, Walls and Glass all leave behind "Ghost" Light Sources when broken

**Comment by flori-schwa** [comment]
More blocks can now be turned into Light sources in release [1.10](https://github.com/flori-schwa/VarLight/releases/tag/1.10)
