### ISSUE TITLE
Server Workers Dying When Modifying Light

### ISSUE THREAD

**Issue by supertakeru** [flori-schwa/VarLightOld#29]
https://pastebin.com/B9Jpxk1E
Stacktrace

**Comment by flori-schwa** [comment]
What were you doing so I can try to recreate the bug?

**Comment by supertakeru** [comment]
I have no idea, sorry man!

This bug just popped up before my server crashed and I wanted to let you know. Wondering if it was anything that you knew or could recognize.

**Comment by flori-schwa** [comment]
I slightly changed the way light is updated, hopefully this will fix your issue (see the dev branch). Can you try to re-create the issue with the attached build?

[VarLight test versions.zip](https://github.com/flori-schwa/VarLight/files/4321300/VarLight.test.versions.zip)

**Comment by supertakeru** [comment]
It was a very rare bug to encounter in the first place, so I am not sure how to re-create it. However, I promise you that if I come across it again with this dev version, I will open another ticket for you to examine. Thanks alot for the timely response! You're doing great, will close until further notice.

**Comment by flori-schwa** [comment]
[Multiple people seem to have this issue](https://www.spigotmc.org/threads/varlight.362135/page-8#post-3717434)
