### ISSUE TITLE
Feature request: View permission

### ISSUE THREAD

**Issue by SlimeDog** [flori-schwa/VarLightOld#34]
Please consider adding a permission to view a (specific) light source. Use case: VIP (for example) can see the light, other (lower) ranks cannot.

Is this possible?

**Comment by flori-schwa** [comment]
This would be pretty difficult to implement, because there is only one Lighting Engine on the server. I'd have to somehow create a Lighting Engine for every single player connected to the server.

**Comment by SlimeDog** [comment]
Not worth the effort. Thanks for fast response.
