### ISSUE TITLE
issue with newest paper?

### ISSUE THREAD

**Issue by supertakeru** [flori-schwa/VarLightOld#35]
https://paste.gg/p/anonymous/456a2b1b2c864c2389fd04e3086f445c

**Comment by flori-schwa** [comment]
This is not a paper issue an will be fixed in the released (See [dev branch](https://github.com/flori-schwa/VarLight/tree/dev))

**Comment by supertakeru** [comment]
not sure if this is useful for you:
https://imgur.com/a/AoQ1X1E

**Comment by flori-schwa** [comment]
Yeah, that's what its using now (on dev branch)

**Comment by supertakeru** [comment]
could you compile this as a dev jar

**Comment by flori-schwa** [comment]
Some features are not fully implemented yet on dev branch (mainly command stuff), but here is a build to use for testing: https://www.spigotmc.org/threads/varlight.362135/page-10#post-3793919

**Comment by flori-schwa** [comment]
Fixed in [1.10.2](https://github.com/flori-schwa/VarLight/releases/tag/1.10.2)
