### ISSUE TITLE
[BUG] Glass

### ISSUE THREAD

**Issue by Aeyori** [flori-schwa/VarLightOld#36]
**Describe the bug**
I can't apply light to glass blocks
**To Reproduce**
Try to right click glowstone on glass blocks
**Expected behavior**
It should increase light level of block
**Screenshots**

**Server setup (please complete the following information):**
 - Minecraft Version (run `/version` ingame):  1.15 Paper
 - VarLight Version (run `/version VarLight` ingame): 1.11.2
 - Java Version (run `java -version` in the terminal): java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

**Additional context**

**Comment by flori-schwa** [comment]
The problem with glass is that, you can apply the custom light level, but breaking the block leaves a ghost light source, sorry.
