### ISSUE TITLE
Plugin stops undiscovered end cities from generating [BUG] 

### ISSUE THREAD

**Issue by tiaan-va** [flori-schwa/VarLightOld#37]
I do not want to be the bearer of bad news but I have discovered a pretty big bug with the plugin. I don't know if this was the case with previous versions of minecraft and the plugin but I it happens with the current version in 1.16.1.

The plugin stops news end cities from generating in unexplored chunks which is a pretty major thing. It will not affect end cities that has already been discovered ans saved to your region files prior to installing the plugin but it stops the generation for any still out there. If you find it hard to believe, teleport yourself to an existing end city in your world, and look at it. Log out, stop the server, and delete the region files for the end dimension (in order to force the game to regenerate structures). Start the server back up, log in, and the end city that was previously there is now gone. If you do the /locate endcity command, it will still tell you that you are literally standing at the end city but it won't be there anymore, and with all region files being reset, the whole dimension will be void of end cities. I discovered this yesterday after I couldn't find a new end city after travelling for hours which then forced me to do the /locate command in order to have exact coords to go to, only to get there and there being no end city at all. I then had to do the painstaking task of removing all my plugins one by one, deleting my end region files and rebooting the server until I finally discovered that varlight was the culprit which was sadly one of the last plugins I tried to remove in my quest haha.

**Comment by flori-schwa** [comment]
Confirmed

![](https://i.imgur.com/lIT0QjH.jpg)
![](https://i.imgur.com/fOEnaaQ.jpg)

this is _slightly_ concerning

**Comment by tiaan-va** [comment]
Villages in the overworld seem to be affected in the same way that end cities are. Nether fortresses and strongholds seem fine as far as I can tell.

**Comment by flori-schwa** [comment]
The cause was the Custom Datapack, no Idea exactly why, but I just decided to hardcode the allowed blocks directly instead of using a datapack instead.
