### ISSUE TITLE
[Feature Request] Adding an command/file to find location for light

### ISSUE THREAD

**Issue by jahangir6969** [flori-schwa/VarLightOld#38]
**Is your feature request related to a problem? Please describe.**

Not much of an problem and more just annoying. The issue i am finding is that when using the plugin to doing with lighting. myself or my team are having issue finding the light source afterwards. If we have commmands or an files it keep in the the folder of the plugin it be more useful

**Describe the solution you'd like**

Just to added an command/config to find location where the light source has worked.

**Comment by flori-schwa** [comment]
You can use `/varlight debug list chunk|region [chunk/region x] [chunk/region z] [page]` to find custom light sources.

Examples:
 - `/varlight debug list chunk`: Lists all light sources in your current chunk
 - `/varlight debug list chunk 0 1`: Lists all light sources in Chunk (0, 1)
 - `/varlight debug list region 0 0`: Lists all light sources in Region (0, 0), containing all chunks from (0, 0) to (31, 31)

If there are more than 10 Light sources, the result will be split among multiple pages, and you can view the other pages by supplying the page as the last parameter when explicitly specifying chunk/region coordinates:

 - `/varlight debug list chunk 0 0 3`: Shows page 3 of all light sources contained in chunk (0, 0)
 - `/varlight debug list region -1 -1 5`: Shows page 5 of all light sources contained in region (-1, -1), containing all chunks from (-32, -32) to (-1, -1) *(You can use [Dinnerbone's Coordinate Tool](https://dinnerbone.com/minecraft/tools/coordinates/) to calculate the exact region coordinates of a chunk/block)*

In the list, you can click on the coordinate locations to directly teleport to the custom light source.

I thought about allowing custom light sources to be visibly highlighted (Using glowing shulkers (?)), but if you have too many light sources, this would certainly impact performance a lot
