### ISSUE TITLE
MultiVerse incompatability 

### ISSUE THREAD

**Issue by SlimeDog** [flori-schwa/VarLightOld#7]
Spigot 1.14.4 latest
VarLight 1.4.1 for Spigot 1.14.4

```
>varlight whitelist list
[15:22:09] [Server thread/INFO]: [VarLight] Worlds on the VarLight Whitelist:
[15:22:09] [Server thread/INFO]:    - "world_whitedog"
>varlight create world_whitedog 271 70 255 15
[15:22:11] [Server thread/INFO]: [VarLight] VarLight is not active in that world!
```

**Comment by flori-schwa** [comment]
Was that world loaded using multiverse or a similar plugin?

**Comment by SlimeDog** [comment]
Of course. MultiVerse-Core latest dev build 4.1.0-b773 

https://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/

Same issue on Spigot 1.13.2 final (added to initial description).

**Comment by flori-schwa** [comment]
Yeah, I already know about the incompatibility with multiverse. I'll get to fixing it soon. Just wanted to confirm that that was causing the issue.

**Comment by SlimeDog** [comment]
Just curious: What multi-world manager is it compatible with now?

**Comment by flori-schwa** [comment]
I have not tested that, I have only confirmed the incompatibility with multiverse.

**Comment by SlimeDog** [comment]
So at the moment, the only world it works in, is "world" ?

**Comment by SlimeDog** [comment]
Issue still exists:
- VarLight 1.4.2-1.13.2 on Spigot 1.13.2 final
- VarLight 1.4.2-1.14.4 on Spigot 1.14.4 latest

Multiverse-Core 4.1.0-SNAPSHOT-b773

**Comment by flori-schwa** [comment]
I know, that is next on the agenda.
